#
# ESLint configuration, http://eslint.org/docs/user-guide/configuring.
#

root: true

parserOptions:
  ecmaVersion: 6
  sourceType: "module" # Indicates that we are using ES6 modules.
  impliedStrict: true # All code will be treated as being in strict mode.

#
# http://eslint.org/docs/rules
#
rules:

  #
  # http://eslint.org/docs/rules/#possible-errors
  #

  # http://eslint.org/docs/rules/semi
  semi: ["error", "always"]

  # http://eslint.org/docs/rules/no-cond-assign
  no-cond-assign: ["error", "always"]

  # http://eslint.org/docs/rules/no-console
  no-console: ["warn"]

  # http://eslint.org/docs/rules/no-constant-condition
  no-constant-condition: ["error"]

  # http://eslint.org/docs/rules/no-control-regex
  no-control-regex: ["error"]

  # http://eslint.org/docs/rules/no-debugger
  no-debugger: ["warn"]

  # http://eslint.org/docs/rules/no-dupe-args
  no-dupe-args: ["error"]

  # http://eslint.org/docs/rules/no-dupe-keys
  no-dupe-keys: ["error"]

  # http://eslint.org/docs/rules/no-duplicate-case
  no-duplicate-case: ["error"]

  # http://eslint.org/docs/rules/no-empty-character-class
  no-empty-character-class: ["error"]

  # http://eslint.org/docs/rules/no-empty
  no-empty: ["error"]

  # http://eslint.org/docs/rules/no-ex-assign
  no-ex-assign: ["error"]

  # http://eslint.org/docs/rules/no-extra-boolean-cast
  no-extra-boolean-cast: ["error"]

  # http://eslint.org/docs/rules/no-extra-parens
  no-extra-parens: ["error"]

  # http://eslint.org/docs/rules/no-extra-semi
  no-extra-semi: ["error"]

  # http://eslint.org/docs/rules/no-func-assign
  no-func-assign: ["error"]

  # http://eslint.org/docs/rules/no-inner-declarations
  no-inner-declarations: ["error"]

  # http://eslint.org/docs/rules/no-invalid-regexp
  no-invalid-regexp: ["error"]

  # http://eslint.org/docs/rules/no-irregular-whitespace
  no-irregular-whitespace: ["error"]

  # http://eslint.org/docs/rules/no-obj-calls
  no-obj-calls: ["error"]

  # http://eslint.org/docs/rules/no-prototype-builtins
  no-prototype-builtins: ["error"]

  # http://eslint.org/docs/rules/no-regex-spaces
  no-regex-spaces: ["error"]

  # http://eslint.org/docs/rules/no-sparse-arrays
  no-sparse-arrays: ["error"]

  # http://eslint.org/docs/rules/no-template-curly-in-string
  no-template-curly-in-string: ["error"]

  # http://eslint.org/docs/rules/no-unexpected-multiline
  no-unexpected-multiline: ["error"]

  # http://eslint.org/docs/rules/no-unreachable
  no-unreachable: ["error"]

  # http://eslint.org/docs/rules/no-unsafe-finally
  no-unsafe-finally: ["error"]

  # http://eslint.org/docs/rules/no-unsafe-negation
  no-unsafe-negation: ["error"]

  # http://eslint.org/docs/rules/use-isnan
  use-isnan: ["error"]

  # http://eslint.org/docs/rules/valid-jsdoc
  valid-jsdoc: ["error"]

  # http://eslint.org/docs/rules/valid-typeof
  valid-typeof: ["error"]

  #
  # http://eslint.org/docs/rules/#best-practices
  #

  #
  # http://eslint.org/docs/rules/#strict-mode
  #

  #
  # http://eslint.org/docs/rules/#variables
  #

  #
  # http://eslint.org/docs/rules/#nodejs-and-commonjs
  #

  #
  # http://eslint.org/docs/rules/#stylistic-issues
  #

  # http://eslint.org/docs/rules/indent
  indent: ["error", 2]

  # http://eslint.org/docs/rules/quotes
  quotes: ["error", "double"]

  #
  # http://eslint.org/docs/rules/#ecmascript-6
  #

env:
  browser: true
  es6: true

#globals:
