#
# ESLint Configuration, http://eslint.org/docs/user-guide/configuring.
#

extends: "eslint:recommended"

parserOptions:
  ecmaVersion: 6
  impliedStrict: true # All code will be treated as being in strict mode.
  sourceType: "module" # Indicates that we are using ES6 modules.

env:
  browser: true
  es6: true
  jasmine: true
  node: true

rules:
  quotes:
  - "error"
  - "double"
